<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<SupportedOSPlatformVersion Condition="'$(SupportedOSPlatformVersion)' == ''">10.0.17763.0</SupportedOSPlatformVersion>
	<TargetPlatformMinVersion Condition="'$(TargetPlatformMinVersion)' == ''">10.0.17763.0</TargetPlatformMinVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="3.119.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SevenWonders.Common\SevenWonders.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>SevenWonders.Game.Engine_UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
